# Example YAML to get you started quickly.
# Be aware that YAML has indentation based scoping.
# Code completion support is available so start typing for available options.
swagger: '2.0'

# This is your document metadata
info:
  version: "2.0.0"
  title: Kontrol API Intercom
host: api.alpha.kichink.com
schemes:
  - http
consumes:
  - application/x-www-form-urlencoded

# Describe your paths here
paths:
  # This is a path endpoint. Change it.
 /kontrol/intercom:
    # This is a HTTP operation
    get:
      summary: user profile
      # Describe this verb here. Note: you can use markdown
      description: |
        Return user profile.
      tags:
        - Intercom
      # This is array of GET operation parameters:
      parameters:
        -
          name: X-API-KEY
          in: header
          description: json web token
          required: true
          type: string
        -
          name: X-STORE-ID
          in: header
          description: store id used
          required: true
          type: string
      # Expected responses for this operation:
      responses:
        # Response code
        200:
          description: Successful response
          # A schema describing your response object.
          # Use JSON Schema format
          schema:
            type: object
            properties:
              data:
                type: object
                properties:
                  facebook:
                    type: integer
                    description: id app fb
                  last_updated:
                    type: integer
                    description: user id
                  store_id:
                    type: string
                    description: store id
                  total_orders:
                    type: string
                    description: user id
                  total_sales:
                    type: string
                    description: user id
                  avg_confirm_delivery:
                    type: string
                    description: user id
                  perc_empty_carts:
                    type: string
                    description: user id
                  payment_data:
                    type: integer
                    description: user id
                  custom_logo:
                    type: integer
                    description: user id
                  cop:
                    type: integer
                    description: user id
                  name:
                    type: string
                    description: store name
                  created:
                    type: string
                    description: store created
                  live:
                    type: string
                    description: user id
                  item_count:
                    type: integer
                    description: user id
                  live_item_count:
                    type: integer
                    description: user id
                  low_inv_count:
                    type: integer
                    description: user id
                  requested_publication:
                    type: integer
                    description: user id
                  first_sale:
                    type: string
                    description: user id
                  last_sale:
                    type: string
                    description: user id
              function:
                type: string
                description: the call path
              result_count:
                type: string
                description: the count result
              response_time:
                type: string
                description: the response time
              status:
                type: string
                description: the status
              http_code:
                type: string
                description: the http code